### ISSUE TITLE
Conflict with csquotes active quotes

### ISSUE THREAD

**Issue by marczellm** [uliska/lilyglyphs#94]
I use LuaTeX 1.0.4 on MiKTeX on Windows 10 x64, and the CTAN version of `lilyglyphs`.

When I compile

    \documentclass{article}
    \usepackage{fontspec, csquotes, lilyglyphs}
    \MakeOuterQuote{"}
    \EnableQuotes
    \begin{document}
    \wholeNote
    \end{document}

I get an error saying

    ! Missing number, treated as zero.
    <to be read again>
    \begingroup
    l.9 \end
          {document}

**Comment by uliska** [comment]
Thank you for the report, I hadn't run into this so far.

To start pinning it down:

* It works with XeLaTeX
* It works with other commands like `lilyDynamics` or `twoBeamedQuavers` or `\lilyText`

Obviously the issue is when loading a glyph by its name.
I suspect [this code] in `core/genericAccess.inp`

```tex
\ifluatex
% ...
\def\lilyGetGlyph#1{\directlua{documentdata.fontchar "#1"}}
\fi
```

to be the culprit but currently don't have a clue how to fix the issue.
@davebellows do you have an idea?

**Comment by uliska** [comment]
https://tex.stackexchange.com/questions/367917/csquotes-conflicts-with-quotation-marks-in-lua-code

**Comment by uliska** [comment]
So the bug is fixed, but I can't tell for sure when it will be in the CTAN version (and when it will be available in TeXLive etc.
